# Generated by Django 5.0.14 on 2026-08-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_category_user_collection_user_memory_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='watch_status',
            field=models.CharField(blank=True, choices=[('want_to_watch', 'Want to Watch'), ('watching', 'Watching'), ('watched', 'Watched')], default='want_to_watch', max_length=20),
        ),
    ]
