# Generated by Django 5.0.14 on 2026-09-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='reminder_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
